### ISSUE TITLE
Home Assistant Core 2024.2.0 - missing dependencies

### ISSUE THREAD

**Issue by longer83** [tmjo/ha-norwegianweather#4]
After updating to HA Core 2024.2.0 integration stopped working with following error in logs:

```
Logger: homeassistant.setup
Source: setup.py:221
First occurred: 22:49:32 (1 occurrences)
Last logged: 22:49:32

Setup failed for custom integration 'norwegianweather': Requirements for norwegianweather not found: ['matplotlib>=3.3.3'].
```

**Comment by tmjo** [comment]
Thanks for reporting, I'll take a look.

**Comment by cg089** [comment]
+1

**Comment by tmjo** [comment]
Don't have a solution yet, but I see there are several other integrations having the same issue (ex #[here](https://github.com/home-assistant/core/issues/109961)). So there's something going on the with installation of Matplotlib as dependency, and I'm guessing it is related to the Python 3.12 update that came together with 2024.2. I've asked on Discord, but so far no clever replies.

**Comment by tmjo** [comment]
Just an update on this: Seems like this is a genereic HA/Matplotlib compatibility and that there is a solution soon to be implemented [here](https://github.com/home-assistant/core/pull/110706).

**Comment by tmjo** [comment]
The issue should be solved with the release of HA 2024.2.3. Please update Home Assistant. Additionally, some improvements to API call and error handling were added in v0.1.6 of this integration. Kindly update both integration and HA and let me know if everthing looks good.

**Comment by cg089** [comment]
I can confirm it works! Thank you for your work and for your very fast replies! Highly appreciated!

**Comment by longer83** [comment]
Unfortunately still doesn't work with my HA:
```
Logger: homeassistant.setup
Source: setup.py:221
First occurred: 08:27:17 (1 occurrences)
Last logged: 08:27:17

Setup failed for custom integration 'norwegianweather': Requirements for norwegianweather not found: ['matplotlib>=3.3.3'].
```
Norwegian Weather version: 0.1.6

Core: 2024.2.4
Supervisor: 2024.02.0
Operating System: 12.0
User interface: 20240207.1

**Comment by tmjo** [comment]
Thanks for reporting. I've got the same issue over at [norwegiantide](https://github.com/tmjo/ha-norwegiantide/issues/8) - solved on my three instances, but not for all. I also see other integrations complaining in the original HA-thread.

**Comment by tmjo** [comment]
Guys, which hardware are you running HA on?

**Comment by TinkerThor** [comment]
Home Assistant Yellow (Rpi4)

**Comment by tmjo** [comment]
@cg089; which hardware are you running? I'm on NUC myself, and seems like most people reporting trouble are on Rpi, so I think this is relevant somehow. The last matplatlib pinning in HA was due to a problem with arm-processors.

**Comment by cg089** [comment]
> @cg089; which hardware are you running? I'm on NUC myself, and seems like most people reporting trouble are on Rpi, so I think this is relevant somehow. The last matplatlib pinning in HA was due to a problem with arm-processors.

I'm on a Windows Server 2022 Hyper-V virtual machine.

**Comment by tmjo** [comment]
I've opened an issue over at HA to [request help](https://github.com/home-assistant/core/issues/111732).

**Comment by longer83** [comment]
> Guys, which hardware are you running HA on?

Raspberry Pi 4B
